# Generated by Django 4.1 on 2024-07-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline",)},
        ),
    ]
